# Generated by Django 5.0.2 on 2024-02-20 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FoodColoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_release', models.DateField(auto_now_add=True)),
                ('minimum_age_for_consumption', models.IntegerField()),
                ('recommended_age_for_consumption', models.IntegerField()),
                ('recommended_intake', models.CharField(max_length=100)),
                ('additives', models.ManyToManyField(to='foodsafety.additive')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsafety.company')),
                ('food_colorings', models.ManyToManyField(to='foodsafety.foodcoloring')),
                ('ingredients', models.ManyToManyField(to='foodsafety.ingredient')),
            ],
        ),
    ]
