# Generated by Django 5.0.2 on 2024-02-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsafety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='energy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='fibers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='fruit_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('solid', 'Solid'), ('beverage', 'Beverage')], default='solid', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sodium',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='sugar',
            field=models.FloatField(default=0.0),
        ),
    ]
